title: Juan Valencia
description: Personal website for Juan Valencia; PhD scholar in The Netherlands. Engineer, swimmer, and amateur surfer.
show_downloads: false
google_analytics: false
theme: jekyll-theme-minimal
