title: Juan Valencia
![Thumbnail of minimal](juan.png)
description: Personal website for Juan Valencia; PhD scholar in The Netherlands. Swimmer and amateur surfer.
show_downloads: false
google_analytics: false
theme: jekyll-theme-minimal
