title: Juan Valencia
description: Personal website for Juan Valencia; System Engineer and PhD scholar in The Netherlands. Engineer, swimmer, runner, and cyclist.
show_downloads: false
google_analytics: false
theme: jekyll-theme-minimal
